<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionSeeder extends Seeder
{
    public function run(): void
    {
        $permissions = [
            [
                'id' => 230,
                'name' => 'Posts View',
                'guard_name' => 'web',
                'parent_name' => 'Content',
                'alias' => null,
                'icon' => 'PencilSquareIcon',
                'created_at' => '2025-09-04 03:06:31',
                'updated_at' => '2026-02-14 13:32:29',
            ],
            [
                'id' => 231,
                'name' => 'Posts Create',
                'guard_name' => 'web',
                'parent_name' => 'Content',
                'alias' => null,
                'icon' => 'PencilSquareIcon',
                'created_at' => '2025-09-04 03:07:09',
                'updated_at' => '2026-02-14 13:31:46',
            ],
            [
                'id' => 232,
                'name' => 'Posts Edit',
                'guard_name' => 'web',
                'parent_name' => 'Content',
                'alias' => null,
                'icon' => 'PencilSquareIcon',
                'created_at' => '2025-09-04 03:07:20',
                'updated_at' => '2026-02-14 13:31:42',
            ],
            [
                'id' => 233,
                'name' => 'Posts Delete',
                'guard_name' => 'web',
                'parent_name' => 'Content',
                'alias' => null,
                'icon' => 'PencilSquareIcon',
                'created_at' => '2025-09-04 03:07:35',
                'updated_at' => '2026-02-14 13:30:57',
            ],
            [
                'id' => 234,
                'name' => 'Floors View',
                'guard_name' => 'web',
                'parent_name' => 'Content',
                'alias' => null,
                'icon' => 'PencilSquareIcon',
                'created_at' => '2025-09-04 03:08:17',
                'updated_at' => '2026-02-14 13:32:23',
            ],
            [
                'id' => 235,
                'name' => 'Floors Create',
                'guard_name' => 'web',
                'parent_name' => 'Content',
                'alias' => null,
                'icon' => 'PencilSquareIcon',
                'created_at' => '2025-09-04 03:08:34',
                'updated_at' => '2026-02-14 13:32:24',
            ],
            [
                'id' => 236,
                'name' => 'Floors Edit',
                'guard_name' => 'web',
                'parent_name' => 'Content',
                'alias' => null,
                'icon' => 'PencilSquareIcon',
                'created_at' => '2025-09-04 03:08:42',
                'updated_at' => '2026-02-14 13:32:25',
            ],
            [
                'id' => 237,
                'name' => 'Floors Delete',
                'guard_name' => 'web',
                'parent_name' => 'Content',
                'alias' => null,
                'icon' => 'PencilSquareIcon',
                'created_at' => '2025-09-04 03:08:51',
                'updated_at' => '2026-02-14 13:32:25',
            ],
            [
                'id' => 238,
                'name' => 'Bookmarks View',
                'guard_name' => 'web',
                'parent_name' => 'Content',
                'alias' => null,
                'icon' => 'PencilSquareIcon',
                'created_at' => '2025-09-04 03:09:40',
                'updated_at' => '2026-02-14 13:32:27',
            ],
            [
                'id' => 239,
                'name' => 'Bookmarks Delete',
                'guard_name' => 'web',
                'parent_name' => 'Content',
                'alias' => null,
                'icon' => 'PencilSquareIcon',
                'created_at' => '2025-09-04 03:09:58',
                'updated_at' => '2026-02-14 13:32:28',
            ],
            [
                'id' => 240,
                'name' => 'Admin/Staff View',
                'guard_name' => 'web',
                'parent_name' => 'System',
                'alias' => null,
                'icon' => 'GlobeEuropeAfricaIcon',
                'created_at' => '2025-09-04 03:11:05',
                'updated_at' => '2026-02-14 14:04:12',
            ],
            [
                'id' => 241,
                'name' => 'Admin/Staff Create',
                'guard_name' => 'web',
                'parent_name' => 'System',
                'alias' => null,
                'icon' => 'GlobeEuropeAfricaIcon',
                'created_at' => '2025-09-04 03:11:19',
                'updated_at' => '2026-02-14 14:04:10',
            ],
            [
                'id' => 242,
                'name' => 'Admin/Staff Edit',
                'guard_name' => 'web',
                'parent_name' => 'System',
                'alias' => null,
                'icon' => 'GlobeEuropeAfricaIcon',
                'created_at' => '2025-09-04 03:11:28',
                'updated_at' => '2026-02-14 14:04:02',
            ],
            [
                'id' => 243,
                'name' => 'Admin/Staff Delete',
                'guard_name' => 'web',
                'parent_name' => 'System',
                'alias' => null,
                'icon' => 'GlobeEuropeAfricaIcon',
                'created_at' => '2025-09-04 03:11:37',
                'updated_at' => '2026-02-14 14:03:24',
            ],
            [
                'id' => 244,
                'name' => 'Suppliers View',
                'guard_name' => 'web',
                'parent_name' => 'Partners',
                'alias' => null,
                'icon' => 'BriefcaseIcon',
                'created_at' => '2025-09-04 03:12:15',
                'updated_at' => '2026-02-14 13:29:44',
            ],
            [
                'id' => 245,
                'name' => 'Suppliers Create',
                'guard_name' => 'web',
                'parent_name' => 'Partners',
                'alias' => null,
                'icon' => 'BriefcaseIcon',
                'created_at' => '2025-09-04 03:12:24',
                'updated_at' => '2026-02-14 13:29:45',
            ],
            [
                'id' => 246,
                'name' => 'Suppliers Edit',
                'guard_name' => 'web',
                'parent_name' => 'Partners',
                'alias' => null,
                'icon' => 'BriefcaseIcon',
                'created_at' => '2025-09-04 03:12:36',
                'updated_at' => '2026-02-14 13:29:47',
            ],
            [
                'id' => 247,
                'name' => 'Suppliers Delete',
                'guard_name' => 'web',
                'parent_name' => 'Partners',
                'alias' => null,
                'icon' => 'BriefcaseIcon',
                'created_at' => '2025-09-04 03:12:47',
                'updated_at' => '2026-02-14 13:29:48',
            ],
            [
                'id' => 248,
                'name' => 'Collaborators View',
                'guard_name' => 'web',
                'parent_name' => 'Partners',
                'alias' => null,
                'icon' => 'BriefcaseIcon',
                'created_at' => '2025-09-04 03:17:00',
                'updated_at' => '2026-02-14 13:29:39',
            ],
            [
                'id' => 249,
                'name' => 'Collaborators Create',
                'guard_name' => 'web',
                'parent_name' => 'Partners',
                'alias' => null,
                'icon' => 'BriefcaseIcon',
                'created_at' => '2025-09-04 03:17:15',
                'updated_at' => '2026-02-14 13:29:40',
            ],
            [
                'id' => 250,
                'name' => 'Collaborators Edit',
                'guard_name' => 'web',
                'parent_name' => 'Partners',
                'alias' => null,
                'icon' => 'BriefcaseIcon',
                'created_at' => '2025-09-04 03:17:28',
                'updated_at' => '2026-02-14 13:29:42',
            ],
            [
                'id' => 251,
                'name' => 'Collaborators Delete',
                'guard_name' => 'web',
                'parent_name' => 'Partners',
                'alias' => null,
                'icon' => 'BriefcaseIcon',
                'created_at' => '2025-09-04 03:17:40',
                'updated_at' => '2026-02-14 13:29:43',
            ],
            [
                'id' => 252,
                'name' => 'Distributors View',
                'guard_name' => 'web',
                'parent_name' => 'Partners',
                'alias' => null,
                'icon' => 'BriefcaseIcon',
                'created_at' => '2025-09-04 03:18:32',
                'updated_at' => '2026-02-14 13:29:35',
            ],
            [
                'id' => 253,
                'name' => 'Distributors Create',
                'guard_name' => 'web',
                'parent_name' => 'Partners',
                'alias' => null,
                'icon' => 'BriefcaseIcon',
                'created_at' => '2025-09-04 03:18:46',
                'updated_at' => '2026-02-14 13:29:36',
            ],
            [
                'id' => 254,
                'name' => 'Distributors Edit',
                'guard_name' => 'web',
                'parent_name' => 'Partners',
                'alias' => null,
                'icon' => 'BriefcaseIcon',
                'created_at' => '2025-09-04 03:18:56',
                'updated_at' => '2026-02-14 13:29:37',
            ],
            [
                'id' => 255,
                'name' => 'Distributors Delete',
                'guard_name' => 'web',
                'parent_name' => 'Partners',
                'alias' => null,
                'icon' => 'BriefcaseIcon',
                'created_at' => '2025-09-04 03:19:07',
                'updated_at' => '2026-02-14 13:29:38',
            ],
            [
                'id' => 256,
                'name' => 'Customers View',
                'guard_name' => 'web',
                'parent_name' => 'Users',
                'alias' => null,
                'icon' => 'UserGroupIcon',
                'created_at' => '2025-09-04 03:19:32',
                'updated_at' => '2026-02-14 13:24:20',
            ],
            [
                'id' => 257,
                'name' => 'Customers Create',
                'guard_name' => 'web',
                'parent_name' => 'Users',
                'alias' => null,
                'icon' => 'UserGroupIcon',
                'created_at' => '2025-09-04 03:20:11',
                'updated_at' => '2026-02-14 13:24:19',
            ],
            [
                'id' => 258,
                'name' => 'Customers Edit',
                'guard_name' => 'web',
                'parent_name' => 'Users',
                'alias' => null,
                'icon' => 'UserGroupIcon',
                'created_at' => '2025-09-04 03:20:20',
                'updated_at' => '2026-02-14 13:24:18',
            ],
            [
                'id' => 259,
                'name' => 'Customers Delete',
                'guard_name' => 'web',
                'parent_name' => 'Users',
                'alias' => null,
                'icon' => 'UserGroupIcon',
                'created_at' => '2025-09-04 03:20:37',
                'updated_at' => '2026-02-14 13:23:33',
            ],
            [
                'id' => 260,
                'name' => 'Categories View',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:21:09',
                'updated_at' => '2026-02-14 13:16:11',
            ],
            [
                'id' => 261,
                'name' => 'Categories Create',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:21:18',
                'updated_at' => '2026-02-14 13:16:07',
            ],
            [
                'id' => 262,
                'name' => 'Categories Edit',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:21:26',
                'updated_at' => '2026-02-14 13:16:02',
            ],
            [
                'id' => 263,
                'name' => 'Categories Delete',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:21:34',
                'updated_at' => '2026-02-14 13:15:56',
            ],
            [
                'id' => 264,
                'name' => 'Smartphones View',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:21:57',
                'updated_at' => '2026-02-14 13:12:30',
            ],
            [
                'id' => 265,
                'name' => 'Smartphones Create',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:22:10',
                'updated_at' => '2026-02-14 13:12:24',
            ],
            [
                'id' => 266,
                'name' => 'Smartphones Edit',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:22:18',
                'updated_at' => '2026-02-14 13:12:13',
            ],
            [
                'id' => 267,
                'name' => 'Smartphones Delete',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:22:25',
                'updated_at' => '2026-02-14 13:11:59',
            ],
            [
                'id' => 268,
                'name' => 'Batches View',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => 'Stock',
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:24:52',
                'updated_at' => '2026-02-14 16:39:04',
            ],
            [
                'id' => 269,
                'name' => 'Batches Create',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => 'Stock',
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:25:03',
                'updated_at' => '2026-02-14 16:39:03',
            ],
            [
                'id' => 270,
                'name' => 'Batches Edit',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => 'Stock',
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:25:14',
                'updated_at' => '2026-02-14 16:39:01',
            ],
            [
                'id' => 271,
                'name' => 'Batches Delete',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => 'Stock',
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:25:25',
                'updated_at' => '2026-02-14 16:39:00',
            ],
            [
                'id' => 272,
                'name' => 'Inventories View',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:52:33',
                'updated_at' => '2026-02-14 13:15:50',
            ],
            [
                'id' => 273,
                'name' => 'Inventories Edit',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:52:56',
                'updated_at' => '2026-02-14 13:15:45',
            ],
            [
                'id' => 274,
                'name' => 'Inventories Delete',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:53:16',
                'updated_at' => '2026-02-14 13:15:35',
            ],
            [
                'id' => 275,
                'name' => 'Orders View',
                'guard_name' => 'web',
                'parent_name' => 'Orders',
                'alias' => null,
                'icon' => 'ShoppingCartIcon',
                'created_at' => '2025-09-04 03:55:33',
                'updated_at' => '2025-09-04 03:55:33',
            ],
            [
                'id' => 276,
                'name' => 'Orders Create',
                'guard_name' => 'web',
                'parent_name' => 'Orders',
                'alias' => null,
                'icon' => 'ShoppingCartIcon',
                'created_at' => '2025-09-04 03:55:44',
                'updated_at' => '2025-09-04 03:55:44',
            ],
            [
                'id' => 277,
                'name' => 'Orders Edit',
                'guard_name' => 'web',
                'parent_name' => 'Orders',
                'alias' => null,
                'icon' => 'ShoppingCartIcon',
                'created_at' => '2025-09-04 03:55:53',
                'updated_at' => '2025-09-04 03:55:53',
            ],
            [
                'id' => 278,
                'name' => 'Orders Delete',
                'guard_name' => 'web',
                'parent_name' => 'Orders',
                'alias' => null,
                'icon' => 'ShoppingCartIcon',
                'created_at' => '2025-09-04 03:56:02',
                'updated_at' => '2025-09-04 03:56:02',
            ],
            [
                'id' => 279,
                'name' => 'Package Recordings View',
                'guard_name' => 'web',
                'parent_name' => 'Orders',
                'alias' => null,
                'icon' => 'VideoCameraIcon',
                'created_at' => '2025-09-04 03:55:10',
                'updated_at' => '2026-02-14 10:59:53',
            ],
            [
                'id' => 280,
                'name' => 'Package Recordings Create',
                'guard_name' => 'web',
                'parent_name' => 'Orders',
                'alias' => null,
                'icon' => 'VideoCameraIcon',
                'created_at' => '2025-09-04 03:55:15',
                'updated_at' => '2026-02-14 10:59:51',
            ],
            [
                'id' => 281,
                'name' => 'Package Recordings Delete',
                'guard_name' => 'web',
                'parent_name' => 'Orders',
                'alias' => null,
                'icon' => 'VideoCameraIcon',
                'created_at' => '2025-09-04 03:56:44',
                'updated_at' => '2026-02-14 10:59:55',
            ],
            [
                'id' => 282,
                'name' => 'Smartphone For Sales View',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => 'Sales',
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:57:26',
                'updated_at' => '2026-02-14 16:37:37',
            ],
            [
                'id' => 283,
                'name' => 'Smartphone For Sales Create',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => 'Sales',
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:57:43',
                'updated_at' => '2026-02-14 16:37:35',
            ],
            [
                'id' => 284,
                'name' => 'Smartphone For Sales Edit',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => 'Sales',
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:57:54',
                'updated_at' => '2026-02-14 16:37:34',
            ],
            [
                'id' => 285,
                'name' => 'Smartphone For Sales Delete',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => 'Sales',
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2025-09-04 03:58:03',
                'updated_at' => '2026-02-14 16:37:33',
            ],
            [
                'id' => 286,
                'name' => 'Reward Points View',
                'guard_name' => 'web',
                'parent_name' => 'Users',
                'alias' => null,
                'icon' => 'UserGroupIcon',
                'created_at' => '2025-09-04 03:58:32',
                'updated_at' => '2026-02-14 13:24:25',
            ],
            [
                'id' => 287,
                'name' => 'Reward Points Create',
                'guard_name' => 'web',
                'parent_name' => 'Users',
                'alias' => null,
                'icon' => 'UserGroupIcon',
                'created_at' => '2025-09-04 03:58:41',
                'updated_at' => '2026-02-14 13:24:23',
            ],
            [
                'id' => 288,
                'name' => 'Reward Points Edit',
                'guard_name' => 'web',
                'parent_name' => 'Users',
                'alias' => null,
                'icon' => 'UserGroupIcon',
                'created_at' => '2025-09-04 03:58:53',
                'updated_at' => '2026-02-14 13:24:22',
            ],
            [
                'id' => 289,
                'name' => 'Reward Points Delete',
                'guard_name' => 'web',
                'parent_name' => 'Users',
                'alias' => null,
                'icon' => 'UserGroupIcon',
                'created_at' => '2025-09-04 03:59:02',
                'updated_at' => '2026-02-14 13:24:21',
            ],
            [
                'id' => 290,
                'name' => 'Supplier Commissions View',
                'guard_name' => 'web',
                'parent_name' => 'Finance',
                'alias' => null,
                'icon' => 'BanknotesIcon',
                'created_at' => '2025-09-04 03:59:34',
                'updated_at' => '2026-02-14 13:26:14',
            ],
            [
                'id' => 291,
                'name' => 'Supplier Commissions Edit',
                'guard_name' => 'web',
                'parent_name' => 'Finance',
                'alias' => null,
                'icon' => 'BanknotesIcon',
                'created_at' => '2025-09-04 19:50:11',
                'updated_at' => '2026-02-14 13:26:11',
            ],
            [
                'id' => 292,
                'name' => 'Supplier Commissions Delete',
                'guard_name' => 'web',
                'parent_name' => 'Finance',
                'alias' => null,
                'icon' => 'BanknotesIcon',
                'created_at' => '2025-09-04 19:50:22',
                'updated_at' => '2026-02-14 13:26:09',
            ],
            [
                'id' => 293,
                'name' => 'Collaborator Commissions View',
                'guard_name' => 'web',
                'parent_name' => 'Finance',
                'alias' => null,
                'icon' => 'BanknotesIcon',
                'created_at' => '2025-09-04 19:51:30',
                'updated_at' => '2026-02-14 13:26:06',
            ],
            [
                'id' => 294,
                'name' => 'Collaborator Commissions Edit',
                'guard_name' => 'web',
                'parent_name' => 'Finance',
                'alias' => null,
                'icon' => 'BanknotesIcon',
                'created_at' => '2025-09-04 19:52:11',
                'updated_at' => '2026-02-14 13:26:03',
            ],
            [
                'id' => 295,
                'name' => 'Collaborator Commissions Delete',
                'guard_name' => 'web',
                'parent_name' => 'Finance',
                'alias' => null,
                'icon' => 'BanknotesIcon',
                'created_at' => '2025-09-04 19:52:22',
                'updated_at' => '2026-02-14 13:26:00',
            ],
            [
                'id' => 296,
                'name' => 'Distributor Commissions View',
                'guard_name' => 'web',
                'parent_name' => 'Finance',
                'alias' => null,
                'icon' => 'BanknotesIcon',
                'created_at' => '2025-09-04 19:54:23',
                'updated_at' => '2026-02-14 13:25:58',
            ],
            [
                'id' => 297,
                'name' => 'Distributor Commissions Edit',
                'guard_name' => 'web',
                'parent_name' => 'Finance',
                'alias' => null,
                'icon' => 'BanknotesIcon',
                'created_at' => '2025-09-04 19:54:41',
                'updated_at' => '2026-02-14 13:25:55',
            ],
            [
                'id' => 298,
                'name' => 'Distributor Commissions Delete',
                'guard_name' => 'web',
                'parent_name' => 'Finance',
                'alias' => null,
                'icon' => 'BanknotesIcon',
                'created_at' => '2025-09-04 19:54:50',
                'updated_at' => '2026-02-14 13:25:54',
            ],
            [
                'id' => 299,
                'name' => 'Settings View',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2025-09-04 19:55:20',
                'updated_at' => '2025-09-04 19:55:20',
            ],
            [
                'id' => 300,
                'name' => 'Translation System View',
                'guard_name' => 'web',
                'parent_name' => 'System',
                'alias' => null,
                'icon' => 'GlobeEuropeAfricaIcon',
                'created_at' => '2025-12-28 02:30:45',
                'updated_at' => '2026-02-14 14:04:15',
            ],
            [
                'id' => 301,
                'name' => 'Order Refunds View',
                'guard_name' => 'web',
                'parent_name' => 'Orders',
                'alias' => null,
                'icon' => 'ReceiptRefundIcon',
                'created_at' => '2026-01-27 14:13:37',
                'updated_at' => '2026-02-14 10:58:53',
            ],
            [
                'id' => 302,
                'name' => 'Order Refunds Edit',
                'guard_name' => 'web',
                'parent_name' => 'Orders',
                'alias' => null,
                'icon' => 'ReceiptRefundIcon',
                'created_at' => '2026-01-27 14:13:49',
                'updated_at' => '2026-02-14 10:58:41',
            ],
            [
                'id' => 304,
                'name' => 'Order Address Changes View',
                'guard_name' => 'web',
                'parent_name' => 'Orders',
                'alias' => null,
                'icon' => 'ArrowPathRoundedSquareIcon',
                'created_at' => '2026-01-28 18:20:05',
                'updated_at' => '2026-02-14 10:59:34',
            ],
            [
                'id' => 305,
                'name' => 'Order Address Changes Edit',
                'guard_name' => 'web',
                'parent_name' => 'Orders',
                'alias' => null,
                'icon' => 'ArrowPathRoundedSquareIcon',
                'created_at' => '2026-01-28 18:20:15',
                'updated_at' => '2026-02-14 10:59:32',
            ],
            [
                'id' => 306,
                'name' => 'SystemLogs View',
                'guard_name' => 'web',
                'parent_name' => 'System',
                'alias' => null,
                'icon' => 'GlobeEuropeAfricaIcon',
                'created_at' => '2026-01-29 13:23:29',
                'updated_at' => '2026-02-14 14:04:14',
            ],
            [
                'id' => 307,
                'name' => 'Risk Signals View',
                'guard_name' => 'web',
                'parent_name' => 'System',
                'alias' => null,
                'icon' => 'GlobeEuropeAfricaIcon',
                'created_at' => '2026-01-30 19:57:35',
                'updated_at' => '2026-02-14 14:04:17',
            ],
            [
                'id' => 308,
                'name' => 'Unsettled Accounts View',
                'guard_name' => 'web',
                'parent_name' => 'Finance',
                'alias' => null,
                'icon' => 'BanknotesIcon',
                'created_at' => '2026-01-31 07:29:52',
                'updated_at' => '2026-02-14 13:27:18',
            ],
            [
                'id' => 309,
                'name' => 'Order Cancelations View',
                'guard_name' => 'web',
                'parent_name' => 'Orders',
                'alias' => null,
                'icon' => 'ArchiveBoxXMarkIcon',
                'created_at' => '2026-02-09 08:26:49',
                'updated_at' => '2026-02-14 10:59:18',
            ],
            [
                'id' => 310,
                'name' => 'Order Cancelations Edit',
                'guard_name' => 'web',
                'parent_name' => 'Orders',
                'alias' => null,
                'icon' => 'ArchiveBoxXMarkIcon',
                'created_at' => '2026-02-09 08:27:09',
                'updated_at' => '2026-02-14 10:59:19',
            ],
            [
                'id' => 313,
                'name' => 'Model Names View',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:09:54',
                'updated_at' => '2026-02-14 13:17:31',
            ],
            [
                'id' => 314,
                'name' => 'Colors View',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:10:15',
                'updated_at' => '2026-02-14 13:18:29',
            ],
            [
                'id' => 315,
                'name' => 'Capacity View',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:10:31',
                'updated_at' => '2026-02-14 13:19:01',
            ],
            [
                'id' => 316,
                'name' => 'Conditions View',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:10:52',
                'updated_at' => '2026-02-14 13:19:45',
            ],
            [
                'id' => 317,
                'name' => 'Addon Items View',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:11:05',
                'updated_at' => '2026-02-14 13:20:29',
            ],
            [
                'id' => 318,
                'name' => 'Model Names Create',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:17:39',
                'updated_at' => '2026-02-14 13:17:39',
            ],
            [
                'id' => 319,
                'name' => 'Model Names Edit',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:17:50',
                'updated_at' => '2026-02-14 13:17:50',
            ],
            [
                'id' => 320,
                'name' => 'Model Names Delete',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:18:05',
                'updated_at' => '2026-02-14 13:18:05',
            ],
            [
                'id' => 321,
                'name' => 'Colors Create',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:18:20',
                'updated_at' => '2026-02-14 13:18:20',
            ],
            [
                'id' => 322,
                'name' => 'Colors Edit',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:18:38',
                'updated_at' => '2026-02-14 13:18:38',
            ],
            [
                'id' => 323,
                'name' => 'Colors Delete',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:18:49',
                'updated_at' => '2026-02-14 13:18:49',
            ],
            [
                'id' => 324,
                'name' => 'Capacity Create',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:19:13',
                'updated_at' => '2026-02-14 13:19:13',
            ],
            [
                'id' => 325,
                'name' => 'Capacity Edit',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:19:24',
                'updated_at' => '2026-02-14 13:19:24',
            ],
            [
                'id' => 326,
                'name' => 'Capacity Delete',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:19:33',
                'updated_at' => '2026-02-14 13:19:33',
            ],
            [
                'id' => 327,
                'name' => 'Conditions Create',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:19:56',
                'updated_at' => '2026-02-14 13:19:56',
            ],
            [
                'id' => 328,
                'name' => 'Conditions Edit',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:20:09',
                'updated_at' => '2026-02-14 13:20:09',
            ],
            [
                'id' => 329,
                'name' => 'Conditions Delete',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:20:20',
                'updated_at' => '2026-02-14 13:20:20',
            ],
            [
                'id' => 330,
                'name' => 'Addon Items Create',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:20:39',
                'updated_at' => '2026-02-14 13:20:39',
            ],
            [
                'id' => 331,
                'name' => 'Addon Items Edit',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:20:49',
                'updated_at' => '2026-02-14 13:20:49',
            ],
            [
                'id' => 332,
                'name' => 'Addon Items Delete',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-02-14 13:20:59',
                'updated_at' => '2026-02-14 13:20:59',
            ],
            [
                'id' => 333,
                'name' => 'Data Deletion Requests View',
                'guard_name' => 'web',
                'parent_name' => 'System',
                'alias' => null,
                'icon' => 'GlobeEuropeAfricaIcon',
                'created_at' => '2026-02-14 14:04:50',
                'updated_at' => '2026-02-14 14:05:29',
            ],
            [
                'id' => 334,
                'name' => 'General',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:24:04',
                'updated_at' => '2026-02-14 14:24:04',
            ],
            [
                'id' => 335,
                'name' => 'Dormancy',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:24:11',
                'updated_at' => '2026-02-14 14:24:11',
            ],
            [
                'id' => 336,
                'name' => 'Role',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:24:22',
                'updated_at' => '2026-02-14 14:24:22',
            ],
            [
                'id' => 337,
                'name' => 'AWS',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:24:35',
                'updated_at' => '2026-02-14 14:24:35',
            ],
            [
                'id' => 338,
                'name' => 'Meta',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:24:48',
                'updated_at' => '2026-02-14 14:24:48',
            ],
            [
                'id' => 339,
                'name' => 'Google Maps',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:25:00',
                'updated_at' => '2026-02-14 14:25:00',
            ],
            [
                'id' => 340,
                'name' => 'SMTP',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:25:08',
                'updated_at' => '2026-02-14 14:25:08',
            ],
            [
                'id' => 341,
                'name' => 'NOWPayments',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:25:24',
                'updated_at' => '2026-02-14 14:25:24',
            ],
            [
                'id' => 342,
                'name' => 'Storage Locations',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:25:37',
                'updated_at' => '2026-02-14 14:25:37',
            ],
            [
                'id' => 343,
                'name' => 'Courier Companies',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:25:49',
                'updated_at' => '2026-02-14 14:25:49',
            ],
            [
                'id' => 344,
                'name' => 'Currency',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:26:12',
                'updated_at' => '2026-02-14 14:26:12',
            ],
            [
                'id' => 345,
                'name' => 'Commission',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:26:28',
                'updated_at' => '2026-02-14 14:26:28',
            ],
            [
                'id' => 346,
                'name' => 'Additional Fees',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:26:43',
                'updated_at' => '2026-02-14 14:26:43',
            ],
            [
                'id' => 347,
                'name' => 'Reward Rate',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:26:59',
                'updated_at' => '2026-02-14 14:26:59',
            ],
            [
                'id' => 348,
                'name' => 'Unsettled Account Notifications',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:27:11',
                'updated_at' => '2026-02-14 14:27:11',
            ],
            [
                'id' => 349,
                'name' => 'Return Policy',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:27:24',
                'updated_at' => '2026-02-14 14:27:24',
            ],
            [
                'id' => 350,
                'name' => 'Shipping Policy',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:27:38',
                'updated_at' => '2026-02-14 14:27:38',
            ],
            [
                'id' => 351,
                'name' => 'Privacy Policy',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:27:54',
                'updated_at' => '2026-02-14 14:27:54',
            ],
            [
                'id' => 352,
                'name' => 'Terms of Service',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:28:06',
                'updated_at' => '2026-02-14 14:28:06',
            ],
            [
                'id' => 353,
                'name' => 'Countries',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:28:26',
                'updated_at' => '2026-02-14 14:28:26',
            ],
            [
                'id' => 354,
                'name' => 'Special Countries',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-02-14 14:28:39',
                'updated_at' => '2026-02-14 14:28:39',
            ],
            [
                'id' => 355,
                'name' => 'Platform Commissions View',
                'guard_name' => 'web',
                'parent_name' => 'Finance',
                'alias' => null,
                'icon' => 'BanknotesIcon',
                'created_at' => '2026-03-02 11:42:33',
                'updated_at' => '2026-03-02 11:42:33',
            ],
            [
                'id' => 356,
                'name' => 'Platform Commissions Edit',
                'guard_name' => 'web',
                'parent_name' => 'Finance',
                'alias' => null,
                'icon' => 'BanknotesIcon',
                'created_at' => '2026-03-02 11:42:59',
                'updated_at' => '2026-03-02 11:42:59',
            ],
            [
                'id' => 357,
                'name' => 'Platform Commissions Delete',
                'guard_name' => 'web',
                'parent_name' => 'Finance',
                'alias' => null,
                'icon' => 'BanknotesIcon',
                'created_at' => '2026-03-02 11:43:09',
                'updated_at' => '2026-03-02 11:43:09',
            ],
            [
                'id' => 358,
                'name' => 'Inventories Verification',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-03-04 12:04:42',
                'updated_at' => '2026-03-04 12:04:42',
            ],
            [
                'id' => 359,
                'name' => 'Smartphone Country Price View',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => 'Sales',
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-03-04 20:18:36',
                'updated_at' => '2026-03-04 20:18:36',
            ],
            [
                'id' => 360,
                'name' => 'Smartphone Country Price Create',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => 'Sales',
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-03-04 20:18:46',
                'updated_at' => '2026-03-04 20:18:46',
            ],
            [
                'id' => 361,
                'name' => 'Smartphone Country Price Edit',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => 'Sales',
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-03-04 20:18:55',
                'updated_at' => '2026-03-04 20:18:55',
            ],
            [
                'id' => 362,
                'name' => 'Smartphone Country Price Delete',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => 'Sales',
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-03-04 20:19:05',
                'updated_at' => '2026-03-04 20:19:05',
            ],
            [
                'id' => 363,
                'name' => 'Order Courier Companies View',
                'guard_name' => 'web',
                'parent_name' => 'Orders',
                'alias' => null,
                'icon' => 'TruckIcon',
                'created_at' => '2026-04-16 09:55:18',
                'updated_at' => '2026-04-16 09:55:18',
            ],
            [
                'id' => 364,
                'name' => 'Order Courier Companies Create',
                'guard_name' => 'web',
                'parent_name' => 'Orders',
                'alias' => null,
                'icon' => 'TruckIcon',
                'created_at' => '2026-04-16 09:55:18',
                'updated_at' => '2026-04-16 09:55:18',
            ],
            [
                'id' => 365,
                'name' => 'Order Courier Companies Edit',
                'guard_name' => 'web',
                'parent_name' => 'Orders',
                'alias' => null,
                'icon' => 'TruckIcon',
                'created_at' => '2026-04-16 09:55:18',
                'updated_at' => '2026-04-16 09:55:18',
            ],
            [
                'id' => 366,
                'name' => 'Order Courier Companies Delete',
                'guard_name' => 'web',
                'parent_name' => 'Orders',
                'alias' => null,
                'icon' => 'TruckIcon',
                'created_at' => '2026-04-16 09:55:18',
                'updated_at' => '2026-04-16 09:55:18',
            ],
            [
                'id' => 367,
                'name' => 'Attribution Links View',
                'guard_name' => 'web',
                'parent_name' => 'Attribution',
                'alias' => null,
                'icon' => 'LinkIcon',
                'created_at' => '2026-04-21 08:30:05',
                'updated_at' => '2026-04-21 08:30:05',
            ],
            [
                'id' => 368,
                'name' => 'Attribution Links Create',
                'guard_name' => 'web',
                'parent_name' => 'Attribution',
                'alias' => null,
                'icon' => 'LinkIcon',
                'created_at' => '2026-04-21 08:30:05',
                'updated_at' => '2026-04-21 08:30:05',
            ],
            [
                'id' => 369,
                'name' => 'Attribution Links Edit',
                'guard_name' => 'web',
                'parent_name' => 'Attribution',
                'alias' => null,
                'icon' => 'LinkIcon',
                'created_at' => '2026-04-21 08:30:05',
                'updated_at' => '2026-04-21 08:30:05',
            ],
            [
                'id' => 370,
                'name' => 'Attribution Links Delete',
                'guard_name' => 'web',
                'parent_name' => 'Attribution',
                'alias' => null,
                'icon' => 'LinkIcon',
                'created_at' => '2026-04-21 08:30:05',
                'updated_at' => '2026-04-21 08:30:05',
            ],
            [
                'id' => 371,
                'name' => 'Attribution Rewards View',
                'guard_name' => 'web',
                'parent_name' => 'Attribution',
                'alias' => null,
                'icon' => 'GiftIcon',
                'created_at' => '2026-04-21 08:30:05',
                'updated_at' => '2026-04-21 08:30:05',
            ],
            [
                'id' => 372,
                'name' => 'Attribution Rewards Edit',
                'guard_name' => 'web',
                'parent_name' => 'Attribution',
                'alias' => null,
                'icon' => 'GiftIcon',
                'created_at' => '2026-04-21 08:30:05',
                'updated_at' => '2026-04-21 08:30:05',
            ],
            [
                'id' => 373,
                'name' => 'Attribution Reward Rate',
                'guard_name' => 'web',
                'parent_name' => 'Settings',
                'alias' => null,
                'icon' => 'Cog6ToothIcon',
                'created_at' => '2026-04-21 09:28:35',
                'updated_at' => '2026-04-21 09:28:35',
            ],
            [
                'id' => 374,
                'name' => 'Internal Product Images View',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-05-21 00:00:01',
                'updated_at' => '2026-05-21 00:00:01',
            ],
            [
                'id' => 375,
                'name' => 'Internal Product Images Create',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-05-21 00:00:02',
                'updated_at' => '2026-05-21 00:00:02',
            ],
            [
                'id' => 376,
                'name' => 'Internal Product Images Delete',
                'guard_name' => 'web',
                'parent_name' => 'Products',
                'alias' => null,
                'icon' => 'ArchiveBoxIcon',
                'created_at' => '2026-05-21 00:00:03',
                'updated_at' => '2026-05-21 00:00:03',
            ],
        ];

        // DB::table('permissions')->upsert(
        //     $permissions,
        //     ['id'],
        //     [
        //         'name',
        //         'guard_name',
        //         'parent_name',
        //         'alias',
        //         'icon',
        //         'created_at',
        //         'updated_at',
        //     ]
        // );


        DB::table('permissions')->insertOrIgnore($permissions);
        app(\Spatie\Permission\PermissionRegistrar::class)->forgetCachedPermissions();
    }
}
